### ISSUE TITLE
FAQ Navigability

### ISSUE THREAD

**Issue by acrois** [JohnnyIrvin/JohnnyIrvin.github.io#68]
**Is your feature request related to a problem? Please describe.**
Once you reach a certain amount of FAQ entries, it becomes difficult to navigate the long FAQ page even with a table of contents.

**Describe the solution you'd like**
Consider numbered headers or even questions with a clickable answers dropdown.

**Describe alternatives you've considered**
Potentially floating table of contents that scrolls with the page.

**Additional context**
Preemptive strike.

**Comment by acrois** [comment]
Relates to #57

**Comment by JohnnyIrvin** [comment]
I'm currently using the table structure provided via Markdown, I'll have to see if I can override it.

**Comment by JohnnyIrvin** [comment]
Obsolete
